### PR TITLE
Feat/swarm 3 acc test infra

### PR DESCRIPTION
**Pull request by mavogel**
* Added ACC test infrastructure
* Adapted `travis`
* Fixed tests

Part 3/4 for splitting #31

### CODE REVIEW

**Comment by catsby** [comment]
Same comment as #38 ; if you can show tests passing on this branch, and because these are refactoring and not new things, we can move one assuming tests are passing. Thanks!

**Comment by mavogel** [comment]
@catsby starting from this PR `travis` also executes the ACC tests. See [here](https://travis-ci.org/terraform-providers/terraform-provider-docker/builds/332691241?utm_source=github_status&utm_medium=notification) for the result 😃

**Comment by mavogel** [comment]
@catsby oh nice I did not know that with the nightly run 😃   I personally find it very useful because all Collaborators can run the ACC tests locally. 
1. I was kind of strange to set up with the introduction of private registries in #21. 
1. It's easier for Collaborators to add ACC tests and verify the behavior of the added feature.
1. It's for the Maintainer to the the `travis` output instead of having to run all the ACC test locally before merging.

So yeah let's leave the setup. For #40 I also found it quite useful

**Comment by catsby** [comment]
Most contributors either run tests against the actual Cloud Vendor (at their own costs) or simply don't run them , and we run them later. I imagine if they're contributing a test, they would have ran it 😄 

That said, most cloud vendors don't come in a binary/local install like Docker, so yeah this is great 👍

**Comment by mavogel** [comment]
@catsby #38 is approved and merged. so we can continue here

**Comment by mavogel** [comment]
ping @catsby 😃

**Pull request merged**
