### PR TITLE
Update to Terraform 0.12

### PR DESCRIPTION
**Pull request by mkeeler**
Basically this was just:

```
go get github.com/hashicorp/terraform@v0.12
go mod vendor
go mod tidy
```

I also ran `make test` afterwards to verify the unit tests as well as ran using some tf 0.12 modules I have been working on utilizing dynamic blocks inside the docker_container resource among other things.

### CODE REVIEW

**Comment by mkeeler** [comment]
I have no clue why the vendor changes are so huge. The dependent modules were reduced but it looks like tf 0.12 has a few more large dependencies.

**Comment by mavogel** [comment]
Probably there will be more todo: https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html

**Comment by mkeeler** [comment]
@mavogel That does seem likely. Running the provider with TF_LOG=DEBUG has terraform put out some warnings about using the `LegacyTypeSystem` so its ignoring some inconsistencies. I went searching through the code a bit and it looks like the only way to get rid of those is to implement the `GRPCProviderFunc` instead of `ProviderFunc` which if I understand correctly will get rid of legacy compatibility with versions below tf 0.12.

```
2019/05/23 17:02:18 [WARN] Provider "docker" produced an invalid plan for module.primary_servers.docker_container.server-containers[2], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .start: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .logs: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .must_run: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .restart: planned value cty.StringVal("no") does not match config value cty.NullVal(cty.String)
      - .rm: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .attach: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .log_driver: planned value cty.StringVal("json-file") does not match config value cty.NullVal(cty.String)
```

If there are any specifics you can think of I could help to move this along let me know. I just thought I would open the PR with something that at least seems to functionally work.

**Comment by mkeeler** [comment]
Apparently I needed to run `make testacc` as those look like the ones failing in travis.

**Comment by mavogel** [comment]
Hi @mkeeler  over the weekend I merged a lot of pending PR to the master to have clean state before upgrading to `v0.12`. That's why a lot of conflicts pop up now. Is it fine for you closing this PR and we will a new one based on the current master? I am also in touch with the core devs to find out how to solve the ACC tests.

**Comment by mkeeler** [comment]
I might have a little time traveling to/from HEX next week. If I do I will rebase and try to fix the tests. If someone else gets around to this before me that’s fine too

**Comment by manfredlift** [comment]
Any updates on this? I'd love to see this merged 😄

**Comment by mkeeler** [comment]
@mavogel I rebased, and fixed all the acceptance tests. Mostly it was just swapping attribute syntax and block syntax around in a handful of places. It seems like when using a terraform set type for a resource with the element type being a Resource terraform doesn't want to allow the attribute syntax. So things like:

```hcl
ports = [
   {
     ...
   },
   {
     ...
   }
]
```

now need to become:

```hcl
ports {
   ...
}

ports {
   ...
}
```

Similarly things like:

```hcl
labels {
  "com.docker.somelabel" = "value"
}
```

has to become:

```hcl
labels = {
	"com.docker.somelabel" = "value"
}
```

Another note is that for most of the test fixing I extracted the config snippet into its own file and ran `terraform12 0.12upgrade` on it (`terraform12` being my 0.12 binary as I also have 0.11 installed).

**Comment by hatched-DavidMichon** [comment]
When can we expect the provider 2.0 version to be released?

**Comment by ozbillwang** [comment]
Get the same today, waiting the mere to be released. 

```
Failed to resolve docker provider 1.2.0: no available version is compatible with this version of Terraform
```

**Comment by delaman** [comment]
Not working with 
```powershell
Terraform v0.12.2
```
```terraform
provider "docker" {
  version = "~> 1.2.0"
}
```

Please release a working docker provider that works on terraform 0.12!

**Comment by mavogel** [comment]
will work with @delaman 

```hcl
provider "docker" {
  version = "~> 2.0.0"
}
```

**Pull request merged**
