### PR TITLE
Add support for OCI manifests

### LINKED ISSUE #315: OCI images are not supported
### Terraform Version

v0.13.5

### Expected Behavior

OCI images should be handled properly.

### Actual Behavior

The provider does not send the right accept header when checking an image, hence a registry will respond 404 for an OCI image.

### Steps to Reproduce

```
data "docker_registry_image" "image" {
  name = "dubodubonduponey/coredns:latest"
}
```

### PR DESCRIPTION
**Pull request by dubo-dubon-duponey**
Fix #315 

cc @mavogel 

For reference: https://github.com/opencontainers/image-spec/blob/master/manifest.md

### CODE REVIEW

**Comment by dubo-dubon-duponey** [comment]
Not too sure why the CI is failing (TestAccDockerRegistryImageResource_build)...

**Comment by mavogel** [comment]
Hey, me neither. I could not restart the job in travis. Probably due to permissions. Could you push again (dummy commit) to trigger a new build please.

**Comment by dubo-dubon-duponey** [comment]
@mavogel done - let see

**Comment by dubo-dubon-duponey** [comment]
Ok, not sure what's going on.

@mavogel I see you guys still have (somewhat) support for schema 1 <- this has long been deprecated by upstream, and the registry by default will not even accept these (https://docs.docker.com/registry/configuration/).


It's not completely clear to me if/how that relates to the problem here, but clearly the code in the failing test has some spaghetti around schema1 that makes it hard to figure out and triggers 400 errors from the registry when the fallback path is being triggered, so, if you are open to removing support, it would make things simpler...

Let me know and I would gladly send a PR to atone for my past sins by removing traces of schema1...

**Comment by dubo-dubon-duponey** [comment]
Fixed (I'm an idiot 🤦🏾‍♂️🤦🏾‍♂️🤦🏾‍♂️🤦🏾‍♂️🤦🏾‍♂️).

Proposal to remove schema1 still stands.

**Comment by mavogel** [comment]
No worries. Thanks for the fix :) Sometimes we all do stupid things ;-) (but we're not idiots 🤗)

**Pull request merged**
