### PR TITLE
Docker service support

### PR DESCRIPTION
**Pull request by mikenorgate**

### CODE REVIEW

**Comment by mavogel** [comment]
@mikenorgate I'm just curious... why did you close this PR? I'm working towards adding Docker Swarm capabilities to this provider. You already did great work on this here.

**Comment by mikenorgate** [comment]
@mavogel I didn't mean to create a pull request just yet. I think there is still some work to be done in finishing and testing what I have done. Would be happy to work with you on getting Swarm up and running

**Comment by mavogel** [comment]
@mikenorgate alright great! Let's do it! I'll get your branch merge it with my private repo feat stuff and use it as a base ok.

I also already asked the maintainer of the `go-dockerclient` to make a new release in an [issue](https://github.com/fsouza/go-dockerclient/issues/685). Let's see how things go on 💪

**Comment by mikenorgate** [comment]
@mavogel Great. Would be good to see what gaps are left

**Pull request closed without merging**
