### PR TITLE
Debug issue 237

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
https://github.com/terraform-providers/terraform-provider-docker/issues/237

This issue can't be reproduced at localhost.
I want to run test with debug option.

### CODE REVIEW

**Comment by mavogel** [comment]
> I want to run test with debug option.

Do you mean in travis or in a linux env?

**Comment by suzuki-shunsuke** [comment]
> Do you mean in travis or in a linux env?
I wanted to run the CI on Travis and got the following result.
https://travis-ci.org/terraform-providers/terraform-provider-docker/jobs/635539888?utm_medium=notification&utm_source=github_status

**Comment by mavogel** [comment]
Alright, got it. As mentioned in https://github.com/terraform-providers/terraform-provider-docker/issues/237#issuecomment-573433073 : lets address it separately

**Comment by mavogel** [comment]
Thank for this fix :) I only updated the copy-paste debug messages from the network funcs before pushing to master

**Pull request merged**
