### PR TITLE
Allow use of `source` file instead of content / content_base64

### PR DESCRIPTION
**Pull request by stephenliberty**
This fixes https://github.com/terraform-providers/terraform-provider-docker/issues/239 by allowing the use of just a filename, rather than the content of a file to be loaded into a container. Apparently anything over 4mb will cause an rpc failure in terraform as of 0.12 (or at least that's what I think I read in the codebase)

Note that I am hardly a Golang expert, and muddled through the best I could.

### CODE REVIEW

**Comment by stephenliberty** [comment]
Err, I don't know why the unit test about "endpoint_spec.0.mode" is broken (TestAccDockerService_fullSpec) and could use some guidance on that.

**Comment by stephenliberty** [comment]
@mavogel - nudging on review

**Comment by mavogel** [comment]
Hey @stephenliberty, sorry for the delay in reviewing your PR. Thanks for contributing! I fixed the tests, so could you rebase/merge master first, please?

**Comment by stephenliberty** [comment]
@mavogel - done. Simple test - just see if the container was restarted if the hash changed.

**Pull request merged**
