### PR TITLE
feat/swarm support

### PR DESCRIPTION
**Pull request by mavogel**
## Summary
* this PR will enable support for `docker swarm`. 
A discussion about different approaches in [issue-29](https://github.com/terraform-providers/terraform-provider-docker/issues/29#issuecomment-354289214).
* it expects the `docker swarm` to be already setup like the [terraform-provider-kubernetes](https://www.terraform.io/docs/providers/kubernetes/guides/getting-started.html#kubernetes) does

## Features accomplished
- Dependencies were updated. Sorry for that first. Next time I'll separate or we can agree on ignoring the `vendor` dir 🤔 
- New resources were implemented: `docker_config`, `docker_secret` and `docker_service`. `config` and `secrets` are updateable is desired. See below for details.
   - Updated documentation
   - Added acceptance tests
- An environment for acceptance testing was set up, with a private registry and 2 tagged versions of a service. `travis` runs these tests now as well. 
- Refactorings:
   - Each resource has it's own `_funcs` file
   - Custom hash functions were removed
   - All validations are now in `validations.go` with separate tests. 

## Open Todos
- [x] More tests (e.g updates on services)
- [x] setup private registry for acc tests on `travis` -> fix incorrect reporting of failure
- [x] debug `travis` random build failures
- [x] Bug fixes
- [x] More logging
- [x] update/fix Website docs
- [x] remove custom hash functions
- [x] provide a funcs file for every resource to be consistent
- [x] add `updateable` flag to `config` and `secret`
- [x] remove `TODOs`
- [x] update Docs
- ~~fix `govendor` usage with possible ignoring the `vendor` dir like in `mvn` or `npm`. see [here](https://gocodecloud.com/blog/2016/03/29/go-vendoring-beginner-tutorial/)~~

## Known issues/workarounds
* The Docker API does not yet support a `/stack` endpoint to set up a composition of services. A Feature request was already made [moby-32781](https://github.com/moby/moby/issues/32781)
* `config` and `secret` can be made `updateable` and have to be deleted manually then because it is the only possibility to implement an update mechanism ATM. See [moby-35803](https://github.com/moby/moby/issues/35803) for details and Feature Request. 
My current workaround to update the `config` for a service to add a unique timestamp to each and ignore lifecycle changes on the name:
```hcl
resource "docker_config" "service_config" {
  name       = "${var.service_name}-config-${replace(timestamp(),":", ".")}"
  data       = "${base64encode(data.template_file.service_config_tpl.rendered)}"
  updateable = true

  lifecycle {
    ignore_changes = ["name"]
  }
}
resource "docker_service" "service" {
   # ...
   configs = [
    {
      config_id   = "${docker_config.service_config.id}"
      config_name = "${docker_config.service_config.name}"
      file_name   = "/root/configs/configs.json"
    },
  ]
}
```

### CODE REVIEW

**Comment by catsby** [comment]
Is there any possible/logical way to break this up into smaller PRs? It's hard to reason about and evaluate all of the changes here.

**Comment by mavogel** [comment]
What I could propose for smaller PRs are:
1. Update Dependencies
1. Refactorings:
   - Each resource has it's own `_funcs` file
   - Custom hash functions were removed
   - All validations are now in `validations.go` with separate tests. 
1. An environment for acceptance testing was set up, with a private registry and 2 tagged versions of a service. `travis` runs these tests now as well. 
1. New resources were implemented: `docker_config`, `docker_secret` and `docker_service`. `config` and `secrets` are updateable is desired. See below for details.
   - Updated documentation
   - Added acceptance tests

What do you think about that @catsby ?

**Comment by catsby** [comment]
That sounds reasonable. It's ok for a new resource (or updated one) to include dependency updates as well, my main thing here is that there are several new resources included. If they are viable on their own, then it would be helpful if they were sent individually.

Thanks!

**Comment by catsby** [comment]
Thank you for splitting them up! 


dance

**Pull request closed without merging**
