### PR TITLE
[work in progress] CI revamp

### LINKED ISSUE #100: Add windows and mac build on travis
Travis supports now builds on windows: https://blog.travis-ci.com/2018-10-11-windows-early-release 🎉 

- Add this to build matrix
- Remove `appveyor` configuration

//cc @AndreLouisCaron

### PR DESCRIPTION
**Pull request by dubo-dubon-duponey**
Potentially fix #100 

Work in progress - just testing at this point (on top of https://github.com/terraform-providers/terraform-provider-docker/pull/199 ).

### CODE REVIEW

**Comment by dubo-dubon-duponey** [comment]
This changeset builds on top of #199 and suggests the following:

Build:
 * build for golang 1.13 and golang 1.12
 * removed golang 1.11 (since it's not supported anymore by the go team)
 * "non-blocking-on-fail" build for golang "tip"
 * build natively on windows
 * build natively on mac

Testing:
 * for golang 1.13, on linux

Various:
 * parallelized builds by having one instance per architecture to speed-up the build task
 * task order is optimized to optimize build time
 * cleanup (docker install is only called on tasks where it's useful)

Caveats and open questions:

 * is it worth it to keep building on go 1.12 on all platforms?
 * since this is the travis free tier (as far as I can tell), the project does not have access to that many parallel instances - meaning we do not get the full benefit of parallelizing build since time will be spent just waiting for new instances in the queue (especially mac it seems)
 * it's not possible to *test* on mac, since docker is not available there
 * it's not possible to *test* on windows, since travis apparently provides only windows containers and not LCOW, and since they do not allow experimental flags to be used (eg: --platform)
 * the "build natively on mac and windows" are not super useful at this point (removing them or making them "non-failing" may speed up the process overall)
 * overall running time is about 20 minutes - while the longest running task is still testacc, waiting for mac and windows instances may be taxing (and also waiting for golang1.12-linux)
  * if we want to speed-up test-acc, either make some of the tests parallelizable, or break down the suite in different groups we could run independently

Overall, this proposal is more invasive and does more than #199. 

@mavogel let me know what you think...

**Comment by mavogel** [comment]
Hey, awesome work :) Thanks. I can give you some details about why I chose to build on all platforms: in the past while updating the docker dependencies there was a problem with the solaris platform, which only came to light in hashicorp's build suite, which is run to release the provider. To get faster feedback I added the `scripts/compile.sh`.

> it's not possible to test on windows, since travis apparently provides only windows containers and not LCOW, and since they do not allow experimental flags to be used (eg: --platform)

Yes, it would be a *should* in the future to run the test suite on windows (there is a `.bat` file already). Until now I could test locally on a handy native windows machine. 

> if we want to speed-up test-acc, either make some of the tests parallelizable, or break down the suite in different groups we could run independently

We could later split out the `docker service` tests, because they take up much of the total time.

> is it worth it to keep building on go 1.12 on all platforms?

Yes, but it is not necessary to build it natively. We could make it as one task and just run `make compile ` on a linux vm and build all the binaries there.  

Those are my 50cent @dubo-dubon-duponey . Fine for you merging the compile step into 1?

**Comment by dubo-dubon-duponey** [comment]
Will update this soon.

Thanks!

**Comment by dubo-dubon-duponey** [comment]
Updated, pending travis happiness:

 * removed arch parallelization: all archs are now built in one task
 * made native builds optional

**Pull request merged**
