### PR TITLE
Added complete support for Docker credential helpers

### LINKED ISSUE #252: Please support credsHelper stanza in Docker config
As per https://docs.docker.com/engine/reference/commandline/login/#credential-helpers
could you please add support for `credHelpers` stanza in the docker config.json file?

This would greatly help situations where the primary credsStore (per-user global) is set to `secretservice` or similar but individual ECR repositories are using ecr-login.

Currently the provider fails with such configurations

### Terraform Version
v0.12.20, docker provider is 2.7.0
The code doesn't look at the `credHelpers` section - verified by inspection.

### Affected Resource(s)
- docker provider stanza

### Terraform Configuration Files
```hcl
provider "docker" {
  version = "~> 2.7"

  registry_auth {
    address     = "000000000000.dkr.ecr.eu-west-1.amazonaws.com"
    config_file = pathexpand("~/.docker/config.json")
  }
}
```

`~/.docker/config.json`:
```json
{
	"auths": {
		"000000000000.dkr.ecr.eu-west-1.amazonaws.com": {}
	},
	"credsStore": "secretservice",
	"credHelpers": {
		"000000000000.dkr.ecr.eu-west-1.amazonaws.com": "ecr-login"
	}
}
```

### Debug Output
`plugin.terraform-provider-docker_v2.7.0_x4` plus a timestamp prefixes each line below:
```
Parsing file for registry auths: <home>/.docker/config.json
Parsing Docker config file
Found Docker configs 'map[0000000000.dkr.ecr.eu-west-1.amazonaws.com:{ }]'
Getting auth for registry '0000000000.dkr.ecr.eu-west-1.amazonaws.com' from credential store: 'secretservice'
```

### Expected Behavior
`docker-credential-ecr-login` should be invoked and the credentials should be retrieved by that.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### PR DESCRIPTION
**Pull request by sergei-ivanov**
Reused code from docker CLI to:

- parse docker config file,
- resolve credential managers,
- and retrieve credentials.

Discarded any custom code in the provider that duplicated docker CLI functionality.

Fixes #252

### CODE REVIEW

**Comment by sergei-ivanov** [comment]
I have successfully tested it locally with the following configuration:

```hcl
terraform {
  required_version = ">= 0.12.20"
}

provider "docker" {
  version = "~> 2.8"

  registry_auth {
    address     = "xxxx-yyyy-containers.jfrog.io"
    config_file = pathexpand("~/.docker/config.json")
  }

  registry_auth {
    address     = "123456789012.dkr.ecr.eu-west-1.amazonaws.com"
    config_file = pathexpand("~/.docker/config.json")
  }
}

data "docker_registry_image" "alpine" {
  name = "alpine:latest"
}

data "docker_registry_image" "jfrog" {
  name = "xxxx-yyyy-containers.jfrog.io/jfrog:latest"
}

data "docker_registry_image" "aws" {
  name = "123456789012.dkr.ecr.eu-west-1.amazonaws.com/aws:latest"
}

resource "docker_image" "jfrog" {
  name          = data.docker_registry_image.jfrog.name
  pull_triggers = [data.docker_registry_image.jfrog.sha256_digest]
}

resource "docker_image" "aws" {
  name          = data.docker_registry_image.aws.name
  pull_triggers = [data.docker_registry_image.aws.sha256_digest]
}
```

with the following configuration in `~/.docker/config.json`:

```json
{
	"auths": {
		"123456789012.dkr.ecr.eu-west-1.amazonaws.com": {},
		"xxxx-yyyy-containers.jfrog.io": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.5 (linux)"
	},
	"credsStore": "secretservice",
	"credHelpers": {
		"123456789012.dkr.ecr.eu-west-1.amazonaws.com": "ecr-login"
	}
}
```

Actual registry hosts were obfuscated to protect the innocent.

**Comment by bdellegrazie** [comment]
Any chance of getting this merged?

**Comment by faucherb94** [comment]
Also would like to know if this is going to be merged any time soon 🙂

**Comment by t4ec** [comment]
Any news? I believe this is the only way to support AWS ECR?

**Comment by dinvlad** [comment]
@t4ec I believe ECR is already supported, like so:
```terraform
resource "aws_ecr_repository" "repo" {
  name = "bar"
}

data "aws_ecr_authorization_token" "repo" {}

provider "docker" {
  registry_auth {
    address = aws_ecr_repository.repo.repository_url.split("/")[0]
    username = aws_ecr_authorization_token.repo.user_name
    password = aws_ecr_authorization_token.repo.password
  }
}
```
Or can also create Docker config file, if you'd like to use Docker afterwards outside Terraform:
```terraform
resource "local_file" "ecr_config" {
  filename = "~/.docker/config.json"
  content = jsonencode({
    auths = {
      "https://${aws_ecr_repository.repo.repository_url.split('/')[0]}" = {
        auth = aws_ecr_authorization_token.repo.authorization_token
      }
    }
  })
}
```

**Comment by bdellegrazie** [comment]
This PR was raised nearly 6 months ago - it  works, provides useful functionality and reduces the active code base size by using the CLI of docker to process the file.

The primary issue is making the provider deal with multiple registries in a sane fashion particularly difficult without this patch.

What is the concern with getting this merged / addressed and how can we help?

**Comment by mavogel** [comment]
Hi @bdellegrazie, sorry for the delay. I was the only active maintainer until now and it was a lack of focus.
The plan is now 
- to merge all the other remaining PRs
- migrate the repo & make it community based (I'll add more maintainers)
- migrate to the terraform registry 
- make it TF 0.13 ready

So we can speed up things for the future.
Best Manuel

**Comment by sergei-ivanov** [comment]
@mavogel I can probably help with Terraform plugin SDK v2 migration, if I have time for that.

**Comment by mavogel** [comment]
Awesome @sergei-ivanov I can make you a maintainer as well. I come back to you 👍

**Pull request merged**
