### PR TITLE
Fix #198 (move travis to go1.13)

### LINKED ISSUE #198: ci: update to go 1.13
Update the provide to golang 1.13.
- See `.travis.yml` from [aws-provider](https://github.com/terraform-providers/terraform-provider-aws)
- Adapt readme

### PR DESCRIPTION
**Pull request by dubo-dubon-duponey**
Suggestion to move to golang 1.13 (fix #198).
It's building and testing locally.

Still keeping 1.11 and 1.12 in the travis matrix - no cost for now, since it's building.

Updated readme accordingly.

### CODE REVIEW

**Comment by mavogel** [comment]
Nice :) Thank you. I'll get some feedback on the 11 and 12 version of go, if we still need to support them. Furthermore I was also thinking of splitting the steps like they do in the [travis.yml](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.travis.yml) of the aws provider, because `testacc` and `compile` take a lot of time

```yaml
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      name: "Code UnitTest"
      script: 
        - make vet
        - make test
    - go: "1.13.x"
      name: "Code AccTest"
      script: 
        - <all the docker setup>
        - make testacc
    - go: "1.13.x"
      name: "Binaries compile"
      script: make compile
    - go: "1.13.x"
      name: "Website"
      script: make website-test
```

And we could add those later in another PR:
- make lint 
- make website-lint

What do you  think?

**Comment by dubo-dubon-duponey** [comment]
Ok, updated with split tasks.

Did amend & force push, but it seems travis is not picking it up (the previous check is not even visible anymore) :s <- @mavogel know what's going on?

**Comment by mavogel** [comment]
No idea what's going on 🤔  but AFAICS you moved everything to #202 , so we could close this one

**Comment by mavogel** [comment]
Closing in favor of #202

**Pull request closed without merging**
