### PR TITLE
docker_network data source

### PR DESCRIPTION
**Pull request by captn3m0**
Singular docker_network data source

- [x]  Add tests
- [x] Update documentation
- [x] Test in personal config: https://git.captnemo.in/nemo/nebula/commit/47a34095c6f9b604edbcadf0ac689dc4e8090683

### CODE REVIEW

**Comment by mavogel** [comment]
@captn3m0 I'd love to add this PR but there is kinda need for tests and an updated documentation. Let me know when they're updated :)

**Comment by captn3m0** [comment]
I'm working on them, just not used to writing go so taking some effort

**Comment by hatched-DavidMichon** [comment]
I'd love to use this as well!

**Comment by mavogel** [comment]
@captn3m0 no worries, I can support you on that :) Could you provide your personal config on another source, cuz I cannot access the link. I'll keep you informed if I start working on the tests to finish this PR

**Comment by captn3m0** [comment]
Backup URL for personal config: https://github.com/captn3m0/nebula/commit/47a34095c6f9b604edbcadf0ac689dc4e8090683

**Comment by hatched-DavidMichon** [comment]
Any update on this? Will it make it to the next release?

**Comment by captn3m0** [comment]
I've added a docs page. Don't think I can contribute to the tests.

**Comment by taiidani** [comment]
I'd love this data source as well. Are the tests all that are left? Happy to help build them!

**Comment by captn3m0** [comment]
I've been using this in production for quite some time, and it has been working good enough.

Somewhat related, if you only require name lookups, the new `networks_advanced` argument does the same job.

**Comment by captn3m0** [comment]
Thanks to @taiidani, we have tests now.

**Pull request merged**
